steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/img-studio:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'NEXT_PUBLIC_PROJECT_ID=${_NEXT_PUBLIC_PROJECT_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'NEXT_PUBLIC_VERTEX_API_LOCATION=${_NEXT_PUBLIC_VERTEX_API_LOCATION}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GCS_BUCKET_LOCATION=${_NEXT_PUBLIC_GCS_BUCKET_LOCATION}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GEMINI_MODEL=${_NEXT_PUBLIC_GEMINI_MODEL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SEG_MODEL=${_NEXT_PUBLIC_SEG_MODEL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_EDIT_ENABLED=${_NEXT_PUBLIC_EDIT_ENABLED}'
      - '--build-arg'
      - 'NEXT_PUBLIC_VEO_ENABLED=${_NEXT_PUBLIC_VEO_ENABLED}'
      - '--build-arg'
      - 'NEXT_PUBLIC_VEO_ITV_ENABLED=${_NEXT_PUBLIC_VEO_ITV_ENABLED}'
      - '--build-arg'
      - 'NEXT_PUBLIC_VEO_ADVANCED_ENABLED=${_NEXT_PUBLIC_VEO_ADVANCED_ENABLED}'
      - '--build-arg'
      - 'NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=${_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS}'
      - '--build-arg'
      - 'NEXT_PUBLIC_OUTPUT_BUCKET=${_NEXT_PUBLIC_OUTPUT_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_TEAM_BUCKET=${_NEXT_PUBLIC_TEAM_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GCS_UPLOAD_BUCKET=${_NEXT_PUBLIC_GCS_UPLOAD_BUCKET}'
      - '--build-arg'
      - 'NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=${_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI}'
      - '--build-arg'
      - 'NEXT_PUBLIC_VTO_ENABLED=${_NEXT_PUBLIC_VTO_ENABLED}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push'
    args: ['push', 'gcr.io/$PROJECT_ID/img-studio:latest']

images:
  - 'gcr.io/$PROJECT_ID/img-studio:latest'
