steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/img-studio:latest'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - '_NEXT_PUBLIC_PROJECT_ID=$PROJECT_ID'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - '_NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}'
      - '--build-arg'
      - '_NEXT_PUBLIC_VERTEX_API_LOCATION=${_NEXT_PUBLIC_VERTEX_API_LOCATION}'
      - '--build-arg'
      - '_NEXT_PUBLIC_GCS_BUCKET_LOCATION=${_NEXT_PUBLIC_GCS_BUCKET_LOCATION}'
      - '--build-arg'
      - '_NEXT_PUBLIC_GEMINI_MODEL=${_NEXT_PUBLIC_GEMINI_MODEL}'
      - '--build-arg'
      - '_NEXT_PUBLIC_SEG_MODEL=${_NEXT_PUBLIC_SEG_MODEL}'
      - '--build-arg'
      - '_NEXT_PUBLIC_EDIT_ENABLED=${_NEXT_PUBLIC_EDIT_ENABLED}'
      - '--build-arg'
      - '_NEXT_PUBLIC_VEO_ENABLED=${_NEXT_PUBLIC_VEO_ENABLED}'
      - '--build-arg'
      - '_NEXT_PUBLIC_VEO_ITV_ENABLED=${_NEXT_PUBLIC_VEO_ITV_ENABLED}'
      - '--build-arg'
      - '_NEXT_PUBLIC_VEO_ADVANCED_ENABLED=${_NEXT_PUBLIC_VEO_ADVANCED_ENABLED}'
      - '--build-arg'
      - '_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=${_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS}'
      - '--build-arg'
      - '_NEXT_PUBLIC_OUTPUT_BUCKET=${_NEXT_PUBLIC_OUTPUT_BUCKET}'
      - '--build-arg'
      - '_NEXT_PUBLIC_TEAM_BUCKET=${_NEXT_PUBLIC_TEAM_BUCKET}'
      - '--build-arg'
      - '_NEXT_PUBLIC_GCS_UPLOAD_BUCKET=${_NEXT_PUBLIC_GCS_UPLOAD_BUCKET}'
      - '--build-arg'
      - '_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=${_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI}'
      - '--build-arg'
      - '_NEXT_PUBLIC_VTO_ENABLED=${_NEXT_PUBLIC_VTO_ENABLED}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/img-studio:latest']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/img-studio:latest'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets=GOOGLE_APPLICATION_CREDENTIALS_JSON=gcs-signer-key:latest,FIREBASE_PRIVATE_KEY=firebase-private-key:latest'
      - '--update-env-vars'
      - >-
        FIREBASE_PROJECT_ID=$PROJECT_ID,
        FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL},
        NEXT_PUBLIC_PROJECT_ID=$PROJECT_ID,
        NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY},
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN},
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET},
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID},
        NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID},
        NEXT_PUBLIC_VERTEX_API_LOCATION=${_NEXT_PUBLIC_VERTEX_API_LOCATION},
        NEXT_PUBLIC_GCS_BUCKET_LOCATION=${_NEXT_PUBLIC_GCS_BUCKET_LOCATION},
        NEXT_PUBLIC_GEMINI_MODEL=${_NEXT_PUBLIC_GEMINI_MODEL},
        NEXT_PUBLIC_SEG_MODEL=${_NEXT_PUBLIC_SEG_MODEL},
        NEXT_PUBLIC_EDIT_ENABLED=${_NEXT_PUBLIC_EDIT_ENABLED},
        NEXT_PUBLIC_VEO_ENABLED=${_NEXT_PUBLIC_VEO_ENABLED},
        NEXT_PUBLIC_VEO_ITV_ENABLED=${_NEXT_PUBLIC_VEO_ITV_ENABLED},
        NEXT_PUBLIC_VEO_ADVANCED_ENABLED=${_NEXT_PUBLIC_VEO_ADVANCED_ENABLED},
        NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=${_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS},
        NEXT_PUBLIC_OUTPUT_BUCKET=${_NEXT_PUBLIC_OUTPUT_BUCKET},
        NEXT_PUBLIC_TEAM_BUCKET=${_NEXT_PUBLIC_TEAM_BUCKET},
        NEXT_PUBLIC_GCS_UPLOAD_BUCKET=${_NEXT_PUBLIC_GCS_UPLOAD_BUCKET},
        NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=${_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI},
        NEXT_PUBLIC_VTO_ENABLED=${_NEXT_PUBLIC_VTO_ENABLED}
images:
  - 'gcr.io/$PROJECT_ID/img-studio:latest'
options:
  logging: CLOUD_LOGGING_ONLY
