#!/bin/bash






gcloud builds submit . --config cloudbuild.yaml \
  --project "$PROJECT_ID" \
  --substitutions=\
_SERVICE_NAME="$SERVICE_NAME",\
_DEPLOY_REGION="$DEPLOY_REGION",\
_FIREBASE_CLIENT_EMAIL="$FIREBASE_CLIENT_EMAIL",\
_NEXT_PUBLIC_FIREBASE_API_KEY="$NEXT_PUBLIC_FIREBASE_API_KEY",\
_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN",\
_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET",\
_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID",\
_NEXT_PUBLIC_FIREBASE_APP_ID="$NEXT_PUBLIC_FIREBASE_APP_ID",\
_NEXT_PUBLIC_VERTEX_API_LOCATION="$NEXT_PUBLIC_VERTEX_API_LOCATION",\
_NEXT_PUBLIC_GCS_BUCKET_LOCATION="$NEXT_PUBLIC_GCS_BUCKET_LOCATION",\
_NEXT_PUBLIC_GEMINI_MODEL="$NEXT_PUBLIC_GEMINI_MODEL",\
_NEXT_PUBLIC_SEG_MODEL="$NEXT_PUBLIC_SEG_MODEL",\
_NEXT_PUBLIC_EDIT_ENABLED="$NEXT_PUBLIC_EDIT_ENABLED",\
_NEXT_PUBLIC_VEO_ENABLED="$NEXT_PUBLIC_VEO_ENABLED",\
_NEXT_PUBLIC_VEO_ITV_ENABLED="$NEXT_PUBLIC_VEO_ITV_ENABLED",\
_NEXT_PUBLIC_VEO_ADVANCED_ENABLED="$NEXT_PUBLIC_VEO_ADVANCED_ENABLED",\
_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS="$NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS",\
_NEXT_PUBLIC_OUTPUT_BUCKET="$NEXT_PUBLIC_OUTPUT_BUCKET",\
_NEXT_PUBLIC_TEAM_BUCKET="$NEXT_PUBLIC_TEAM_BUCKET",\
_NEXT_PUBLIC_GCS_UPLOAD_BUCKET="$NEXT_PUBLIC_GCS_UPLOAD_BUCKET",\
_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI="$NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI",\
_NEXT_PUBLIC_VTO_ENABLED="$NEXT_PUBLIC_VTO_ENABLED"
