FROM node:20-alpine AS base

# --- 接收来自 cloudbuild.yaml 的所有构建参数 ---
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_VERTEX_API_LOCATION
ARG NEXT_PUBLIC_GCS_BUCKET_LOCATION
ARG NEXT_PUBLIC_GEMINI_MODEL
ARG NEXT_PUBLIC_SEG_MODEL
ARG NEXT_PUBLIC_EDIT_ENABLED
ARG NEXT_PUBLIC_VEO_ENABLED
ARG NEXT_PUBLIC_VEO_ITV_ENABLED
ARG NEXT_PUBLIC_VEO_ADVANCED_ENABLED
ARG NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS
ARG NEXT_PUBLIC_OUTPUT_BUCKET
ARG NEXT_PUBLIC_TEAM_BUCKET
ARG NEXT_PUBLIC_GCS_UPLOAD_BUCKET
ARG NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI
ARG NEXT_PUBLIC_VTO_ENABLED

WORKDIR /app
COPY package*.json ./
RUN npm install

# 构建器阶段
FROM base AS builder
WORKDIR /app
COPY . .

# --- 将接收到的 ARG 设置为构建时的环境变量 ---
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_VERTEX_API_LOCATION=$NEXT_PUBLIC_VERTEX_API_LOCATION
ENV NEXT_PUBLIC_GCS_BUCKET_LOCATION=$NEXT_PUBLIC_GCS_BUCKET_LOCATION
ENV NEXT_PUBLIC_GEMINI_MODEL=$NEXT_PUBLIC_GEMINI_MODEL
ENV NEXT_PUBLIC_SEG_MODEL=$NEXT_PUBLIC_SEG_MODEL
ENV NEXT_PUBLIC_EDIT_ENABLED=$NEXT_PUBLIC_EDIT_ENABLED
ENV NEXT_PUBLIC_VEO_ENABLED=$NEXT_PUBLIC_VEO_ENABLED
ENV NEXT_PUBLIC_VEO_ITV_ENABLED=$NEXT_PUBLIC_VEO_ITV_ENABLED
ENV NEXT_PUBLIC_VEO_ADVANCED_ENABLED=$NEXT_PUBLIC_VEO_ADVANCED_ENABLED
ENV NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=$NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS
ENV NEXT_PUBLIC_OUTPUT_BUCKET=$NEXT_PUBLIC_OUTPUT_BUCKET
ENV NEXT_PUBLIC_TEAM_BUCKET=$NEXT_PUBLIC_TEAM_BUCKET
ENV NEXT_PUBLIC_GCS_UPLOAD_BUCKET=$NEXT_PUBLIC_GCS_UPLOAD_BUCKET
ENV NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=$NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI
ENV NEXT_PUBLIC_VTO_ENABLED=$NEXT_PUBLIC_VTO_ENABLED

# 在这个充满了正确环境变量的环境中执行构建
RUN npm run build

# 生产运行阶段
FROM node:20-alpine AS runner
WORKDIR /app

USER root
RUN apk update && apk add --no-cache ffmpeg

COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/public ./public
COPY --from=builder --chown=node:node /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

USER node
EXPOSE 3000
CMD ["npm", "start"]
